options:
  logging: CLOUD_LOGGING_ONLY
timeout: 15m
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-south1-docker.pkg.dev/its-ak-392515/test-repo-ak/test-nginx:latest', '.' ]
images:
- 'asia-south1-docker.pkg.dev/its-ak-392515/test-repo-ak/test-nginx:latest'

- name: "gcr.io/cloud-builders/gcloud"
  script: |
    #!/bin/bash
    echo "akshay"


