options:
  logging: CLOUD_LOGGING_ONLY
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-south1-docker.pkg.dev/its-ak-392515/test-repo-ak/test-nginx:latest', '.' ]
images:
- 'asia-south1-docker.pkg.dev/its-ak-392515/test-repo-ak/test-nginx:latest'

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'compute', 'instance-groups', 'managed', 'rolling-action', 'start-update', 'ingrp-1', '--project=$PROJECT_ID', '--type=proactive', '--max-surge=0', '--max-unavailable=1', '--min-ready=0', '--minimal-action=restart', '--most-disruptive-allowed-action=', '--replacement-method=substitute', '--version=template=https://www.googleapis.com/compute/beta/projects/$PROJECT_ID/global/instanceTemplates/temp-l3', '--zone=$ZONE']
substitutions:
  _PROJECT_ID: its-ak-392515
  _ZONE: asia-south1-c

  
