options:
  logging: CLOUD_LOGGING_ONLY
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "bash"
  env:
  - 'GCP_TEMP_INSTANCE_NAME=akshaytemp6'

  args:
    - "-c"
    - |
        echo "testing stage"
        

        GCP_TEMP_SERVICE_AC=415800680409-compute@developer.gserviceaccount.com
        GCP_TEMP_TAG=akshaytemptag
        GCP_CUSTOM_IMAGE=akshayimage
        GCP_USER=akakshaycontact
        GCP_STORAGE_LOCATION=us
        GCP_INSTANCE_TEMPLATE_NAME=akshayinstancetemplate
        GCP_INSTANCE_GROUP_NAME=akshayinstancegroup
        
        GIT_BRANCH=main
        GIT_URL=https://gitlab-ci-token:glpat-ge-GCbBoxF6roysMNKvp@code.ria.rocks/Akshay/piper.git        
        GCP_MIG=akshayinstancegroup
        GCP_ZONE=us-central1-c
        GCP_REGION=us-central1
        GCP_PROJECT_ID=its-ak-392515

        gcloud compute instances create $GCP_TEMP_INSTANCE_NAME --project=$GCP_PROJECT_ID --zone=$GCP_ZONE --machine-type=e2-medium --network-interface=network-tier=PREMIUM,stack-type=IPV4_ONLY,subnet=default --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=$GCP_TEMP_SERVICE_AC --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --tags=$GCP_TEMP_TAG --create-disk=auto-delete=yes,boot=yes,device-name=$GCP_TEMP_INSTANCE_NAME,image=projects/$GCP_PROJECT_ID/global/images/$GCP_CUSTOM_IMAGE,mode=rw,size=10,type=projects/$GCP_PROJECT_ID/zones/$GCP_ZONE/diskTypes/pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --labels=ec-src=vm_add-gcloud --reservation-affinity=any



        
