options:
  logging: CLOUD_LOGGING_ONLY
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "bash"
  args:
    - "-c"
    - |
        echo "testing stage"
        echo ${_GCP_TEMP_INSTANCE_NAME}
        
        gcloud compute instances create ${_GCP_TEMP_INSTANCE_NAME} --project=${_GCP_PROJECT_ID} --zone=${_GCP_ZONE} --machine-type=e2-medium --network-interface=network-tier=PREMIUM,stack-type=IPV4_ONLY,subnet=default --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=${_GCP_TEMP_SERVICE_AC} --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --tags=${_GCP_TEMP_TAG} --create-disk=auto-delete=yes,boot=yes,device-name=${_GCP_TEMP_INSTANCE_NAME},image=projects/${_GCP_PROJECT_ID}/global/images/${_GCP_CUSTOM_IMAGE},mode=rw,size=10,type=projects/${_GCP_PROJECT_ID}/zones/${_GCP_ZONE}/diskTypes/pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --labels=ec-src=vm_add-gcloud --reservation-affinity=any
        
        
        gcloud compute ssh ${_GCP_USER}@${_GCP_TEMP_INSTANCE_NAME} --tunnel-through-iap --zone ${_GCP_ZONE} --command 'mkdir -p /home/${_GCP_USER}/akshay/original' 
        gcloud compute ssh ${_GCP_USER}@${_GCP_TEMP_INSTANCE_NAME} --tunnel-through-iap --zone ${_GCP_ZONE} --command 'cd /home/${_GCP_USER}/akshay/original && git clone -b ${_GIT_BRANCH} ${_GIT_URL} . && ls'
        gcloud compute ssh ${_GCP_USER}@${_GCP_TEMP_INSTANCE_NAME} --tunnel-through-iap --zone ${_GCP_ZONE} --command 'cd /home/${_GCP_USER}/akshay/original && pm2 start server.js && pm2 save'
        
        gcloud compute instances stop ${_GCP_TEMP_INSTANCE_NAME} --zone=${_GCP_ZONE} --quiet
        
        gcloud compute images create ${_GCP_INSTANCE_NAME}-$BUILD_ID --project=${_GCP_PROJECT_ID} --source-disk=${_GCP_TEMP_INSTANCE_NAME} --source-disk-zone=${_GCP_ZONE} --storage-location=${_GCP_STORAGE_LOCATION}
        
        gcloud compute instances delete ${_GCP_TEMP_INSTANCE_NAME} --zone=${_GCP_ZONE} --quiet
            
        gcloud compute instance-templates create ${_GCP_INSTANCE_TEMPLATE_NAME} --project=${_GCP_PROJECT_ID} --machine-type=e2-medium --network-interface=network=default,network-tier=PREMIUM --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=${_GCP_TEMP_SERVICE_AC} --scopes=https://www.googleapis.com/auth/devstorage.read_only,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write,https://www.googleapis.com/auth/servicecontrol,https://www.googleapis.com/auth/service.management.readonly,https://www.googleapis.com/auth/trace.append --tags=${_GCP_TEMP_TAG} --create-disk=auto-delete=yes,boot=yes,device-name=${_GCP_INSTANCE_TEMPLATE_NAME},image=projects/${_GCP_PROJECT_ID}/global/images/${_GCP_INSTANCE_NAME}-$BUILD_ID,mode=rw,size=10,type=pd-balanced --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
        
        gcloud compute instance-groups managed set-instance-template ${_GCP_INSTANCE_GROUP_NAME} --template=${_GCP_INSTANCE_NAME}-$BUILD_ID
            
        gcloud compute instance-groups managed rolling-action restart ${_GCP_INSTANCE_GROUP_NAME}



substitutions:
    _GCP_TEMP_INSTANCE_NAME: akshaytemp8
    _GCP_INSTANCE_NAME: akshayone
    _GCP_TEMP_INSTANCE_NAME: akshaytemp6
    _GCP_TEMP_SERVICE_AC: 415800680409-compute@developer.gserviceaccount.com
    _GCP_TEMP_TAG: akshaytemptag
    _GCP_CUSTOM_IMAGE: akshayimage
    _GCP_USER: akakshaycontact
    _GCP_STORAGE_LOCATION: us
    _GCP_INSTANCE_TEMPLATE_NAME: akshayinstancetemplate
    _GCP_INSTANCE_GROUP_NAME: akshayinstancegroup
    _GIT_BRANCH: main
    _GIT_URL: https://gitlab-ci-token:glpat-ge-GCbBoxF6roysMNKvp@code.ria.rocks/Akshay/piper.git
    _GCP_MIG: akshayinstancegroup
    _GCP_ZONE: us-central1-c
    _GCP_REGION: us-central1
    _GCP_PROJECT_ID: its-ak-392515

        
